
INSERT INTO public.ui_translations (language_code, key, value) VALUES
-- ===== ENGLISH =====
('en', 'nav.cocktails', 'Cocktails'),
('en', 'nav.shots', 'Shots'),
('en', 'nav.non_alcoholic', 'Non-Alcoholic'),
('en', 'nav.ingredients', 'Ingredients'),
('en', 'nav.search', 'Search'),
('en', 'cat.cocktails', 'Cocktails'),
('en', 'cat.shots', 'Shots'),
('en', 'cat.non-alcoholic', 'Non-Alcoholic'),
('en', 'cat.cocktails_desc', 'Classic and contemporary cocktail recipes crafted to perfection.'),
('en', 'cat.shots_desc', 'Quick, bold, and perfect for celebrations.'),
('en', 'cat.non-alcoholic_desc', 'Refreshing mocktails for every occasion.'),
('en', 'seo.home_title', 'Cocktail Craft — Discover Perfect Cocktail Recipes'),
('en', 'seo.home_desc', 'Explore expertly curated cocktail recipes — from timeless classics to bold new creations. Cocktails, shots, and non-alcoholic mocktails.'),
('en', 'seo.search_desc', 'Search cocktail recipes by name, ingredient, tag or equipment.'),
('en', 'hero.craft', 'Craft'),
('en', 'hero.your_perfect', 'Your Perfect'),
('en', 'hero.cocktail', 'Cocktail'),
('en', 'hero.subtitle', 'Discover expertly curated recipes — from timeless classics to bold new creations.'),
('en', 'hero.explore', 'Explore Recipes'),
('en', 'home.featured', 'Featured Recipes'),
('en', 'home.featured_sub', 'Our most popular picks'),
('en', 'home.view_all', 'View all'),
('en', 'common.loading', 'Loading...'),
('en', 'common.all', 'All'),
('en', 'common.back_home', 'Back to Home'),
('en', 'common.show_less', 'Show less'),
('en', 'common.read_more', 'Read more'),
('en', 'recipe.not_found', 'Recipe Not Found'),
('en', 'recipe.ingredients', 'Ingredients'),
('en', 'recipe.recipe', 'Recipe'),
('en', 'recipe.bar_tools', 'Bar Tools'),
('en', 'recipe.recommended', 'Recommended Drinks'),
('en', 'recipe.reviews', 'Reviews'),
('en', 'recipe.tools', 'Tools'),
('en', 'ingredient.not_found', 'Ingredient Not Found'),
('en', 'ingredient.recipes_with', 'Recipes with'),
('en', 'ingredients.subtitle', 'Explore all ingredients used in our recipes.'),
('en', 'search.placeholder', 'Search by name, ingredient, tag, hashtag, equipment...'),
('en', 'search.placeholder_short', 'Search recipes...'),
('en', 'search.results', 'recipe(s) found for'),
('en', 'search.no_results', 'No results found'),
('en', 'search.try_different', 'Try different keywords or browse categories.'),
('en', 'search.start_typing', 'Start typing to search'),
('en', 'search.hint', 'Search by recipe name, ingredient, tag, hashtag, or equipment.'),
('en', 'footer.contact', 'Contact us at'),
('en', 'footer.rights', 'All rights reserved.'),
('en', 'review.your_name', 'Your name'),
('en', 'review.write', 'Write your review...'),
('en', 'review.rating', 'Rating:'),
('en', 'review.submit', 'Submit'),
('en', 'review.sending', 'Sending...'),
('en', 'review.empty', 'No reviews yet. Be the first!'),
('en', 'notfound.title', 'Page not found'),
('en', 'notfound.back', 'Back to Home'),
('en', 'ingredients.no_results', 'No ingredients found'),
('en', 'category.no_more', 'No more recipes'),
('en', 'category.loading_more', 'Loading recipes...'),
-- ===== GERMAN =====
('de', 'nav.cocktails', 'Cocktails'),
('de', 'nav.shots', 'Shots'),
('de', 'nav.non_alcoholic', 'Alkoholfrei'),
('de', 'nav.ingredients', 'Zutaten'),
('de', 'nav.search', 'Suche'),
('de', 'cat.cocktails', 'Cocktails'),
('de', 'cat.shots', 'Shots'),
('de', 'cat.non-alcoholic', 'Alkoholfrei'),
('de', 'cat.cocktails_desc', 'Klassische und moderne Cocktailrezepte, perfekt zubereitet.'),
('de', 'cat.shots_desc', 'Schnell, kräftig und perfekt zum Feiern.'),
('de', 'cat.non-alcoholic_desc', 'Erfrischende Mocktails für jeden Anlass.'),
('de', 'seo.home_title', 'Cocktail Craft — Entdecke perfekte Cocktailrezepte'),
('de', 'seo.home_desc', 'Entdecke sorgfältig kuratierte Cocktailrezepte — von zeitlosen Klassikern bis zu kühnen neuen Kreationen.'),
('de', 'seo.search_desc', 'Suche Cocktailrezepte nach Name, Zutat, Tag oder Barwerkzeug.'),
('de', 'hero.craft', 'Kreiere'),
('de', 'hero.your_perfect', 'Deinen Perfekten'),
('de', 'hero.cocktail', 'Cocktail'),
('de', 'hero.subtitle', 'Entdecke sorgfältig kuratierte Rezepte — von zeitlosen Klassikern bis zu kühnen neuen Kreationen.'),
('de', 'hero.explore', 'Rezepte entdecken'),
('de', 'home.featured', 'Empfohlene Rezepte'),
('de', 'home.featured_sub', 'Unsere beliebtesten Auswahlen'),
('de', 'home.view_all', 'Alle anzeigen'),
('de', 'common.loading', 'Laden...'),
('de', 'common.all', 'Alle'),
('de', 'common.back_home', 'Zurück zur Startseite'),
('de', 'common.show_less', 'Weniger anzeigen'),
('de', 'common.read_more', 'Weiterlesen'),
('de', 'recipe.not_found', 'Rezept nicht gefunden'),
('de', 'recipe.ingredients', 'Zutaten'),
('de', 'recipe.recipe', 'Rezept'),
('de', 'recipe.bar_tools', 'Barwerkzeuge'),
('de', 'recipe.recommended', 'Empfohlene Drinks'),
('de', 'recipe.reviews', 'Bewertungen'),
('de', 'recipe.tools', 'Werkzeuge'),
('de', 'ingredient.not_found', 'Zutat nicht gefunden'),
('de', 'ingredient.recipes_with', 'Rezepte mit'),
('de', 'ingredients.subtitle', 'Alle Zutaten unserer Rezepte entdecken.'),
('de', 'search.placeholder', 'Suche nach Name, Zutat, Tag, Hashtag, Werkzeug...'),
('de', 'search.placeholder_short', 'Rezepte suchen...'),
('de', 'search.results', 'Rezept(e) gefunden für'),
('de', 'search.no_results', 'Keine Ergebnisse gefunden'),
('de', 'search.try_different', 'Versuche andere Suchbegriffe oder durchsuche Kategorien.'),
('de', 'search.start_typing', 'Tippe, um zu suchen'),
('de', 'search.hint', 'Suche nach Rezeptname, Zutat, Tag, Hashtag oder Werkzeug.'),
('de', 'footer.contact', 'Kontaktiere uns unter'),
('de', 'footer.rights', 'Alle Rechte vorbehalten.'),
('de', 'review.your_name', 'Dein Name'),
('de', 'review.write', 'Schreibe deine Bewertung...'),
('de', 'review.rating', 'Bewertung:'),
('de', 'review.submit', 'Absenden'),
('de', 'review.sending', 'Senden...'),
('de', 'review.empty', 'Noch keine Bewertungen. Sei der Erste!'),
('de', 'notfound.title', 'Seite nicht gefunden'),
('de', 'notfound.back', 'Zurück zur Startseite'),
('de', 'ingredients.no_results', 'Keine Zutaten gefunden'),
('de', 'category.no_more', 'Keine weiteren Rezepte'),
('de', 'category.loading_more', 'Rezepte werden geladen...'),
-- ===== FRENCH =====
('fr', 'nav.cocktails', 'Cocktails'),
('fr', 'nav.shots', 'Shots'),
('fr', 'nav.non_alcoholic', 'Sans Alcool'),
('fr', 'nav.ingredients', 'Ingrédients'),
('fr', 'nav.search', 'Recherche'),
('fr', 'cat.cocktails', 'Cocktails'),
('fr', 'cat.shots', 'Shots'),
('fr', 'cat.non-alcoholic', 'Sans Alcool'),
('fr', 'cat.cocktails_desc', 'Recettes de cocktails classiques et modernes, préparées à la perfection.'),
('fr', 'cat.shots_desc', 'Rapides, audacieux et parfaits pour les fêtes.'),
('fr', 'cat.non-alcoholic_desc', 'Mocktails rafraîchissants pour toutes les occasions.'),
('fr', 'seo.home_title', 'Cocktail Craft — Découvrez des recettes de cocktails parfaites'),
('fr', 'seo.home_desc', 'Explorez des recettes de cocktails soigneusement sélectionnées — des classiques intemporels aux créations audacieuses.'),
('fr', 'seo.search_desc', 'Rechercher des recettes de cocktails par nom, ingrédient, tag ou équipement.'),
('fr', 'hero.craft', 'Créez'),
('fr', 'hero.your_perfect', 'Votre Parfait'),
('fr', 'hero.cocktail', 'Cocktail'),
('fr', 'hero.subtitle', 'Découvrez des recettes soigneusement sélectionnées — des classiques intemporels aux créations audacieuses.'),
('fr', 'hero.explore', 'Explorer les recettes'),
('fr', 'home.featured', 'Recettes en vedette'),
('fr', 'home.featured_sub', 'Nos choix les plus populaires'),
('fr', 'home.view_all', 'Tout voir'),
('fr', 'common.loading', 'Chargement...'),
('fr', 'common.all', 'Tout'),
('fr', 'common.back_home', 'Retour à l''accueil'),
('fr', 'common.show_less', 'Voir moins'),
('fr', 'common.read_more', 'Lire la suite'),
('fr', 'recipe.not_found', 'Recette introuvable'),
('fr', 'recipe.ingredients', 'Ingrédients'),
('fr', 'recipe.recipe', 'Recette'),
('fr', 'recipe.bar_tools', 'Ustensiles de bar'),
('fr', 'recipe.recommended', 'Boissons recommandées'),
('fr', 'recipe.reviews', 'Avis'),
('fr', 'recipe.tools', 'Ustensiles'),
('fr', 'ingredient.not_found', 'Ingrédient introuvable'),
('fr', 'ingredient.recipes_with', 'Recettes avec'),
('fr', 'ingredients.subtitle', 'Découvrez tous les ingrédients de nos recettes.'),
('fr', 'search.placeholder', 'Rechercher par nom, ingrédient, tag, hashtag, équipement...'),
('fr', 'search.placeholder_short', 'Rechercher des recettes...'),
('fr', 'search.results', 'recette(s) trouvée(s) pour'),
('fr', 'search.no_results', 'Aucun résultat trouvé'),
('fr', 'search.try_different', 'Essayez d''autres mots-clés ou parcourez les catégories.'),
('fr', 'search.start_typing', 'Commencez à taper pour rechercher'),
('fr', 'search.hint', 'Rechercher par nom de recette, ingrédient, tag, hashtag ou équipement.'),
('fr', 'footer.contact', 'Contactez-nous à'),
('fr', 'footer.rights', 'Tous droits réservés.'),
('fr', 'review.your_name', 'Votre nom'),
('fr', 'review.write', 'Écrivez votre avis...'),
('fr', 'review.rating', 'Note :'),
('fr', 'review.submit', 'Envoyer'),
('fr', 'review.sending', 'Envoi...'),
('fr', 'review.empty', 'Pas encore d''avis. Soyez le premier !'),
('fr', 'notfound.title', 'Page introuvable'),
('fr', 'notfound.back', 'Retour à l''accueil'),
('fr', 'ingredients.no_results', 'Aucun ingrédient trouvé'),
('fr', 'category.no_more', 'Plus de recettes'),
('fr', 'category.loading_more', 'Chargement des recettes...'),
-- ===== POLISH =====
('pl', 'nav.cocktails', 'Koktajle'),
('pl', 'nav.shots', 'Shoty'),
('pl', 'nav.non_alcoholic', 'Bezalkoholowe'),
('pl', 'nav.ingredients', 'Składniki'),
('pl', 'nav.search', 'Szukaj'),
('pl', 'cat.cocktails', 'Koktajle'),
('pl', 'cat.shots', 'Shoty'),
('pl', 'cat.non-alcoholic', 'Bezalkoholowe'),
('pl', 'cat.cocktails_desc', 'Klasyczne i nowoczesne przepisy na koktajle, przygotowane perfekcyjnie.'),
('pl', 'cat.shots_desc', 'Szybkie, mocne i idealne na imprezę.'),
('pl', 'cat.non-alcoholic_desc', 'Orzeźwiające drinki bezalkoholowe na każdą okazję.'),
('pl', 'seo.home_title', 'Cocktail Craft — Odkryj idealne przepisy na koktajle'),
('pl', 'seo.home_desc', 'Przeglądaj starannie wyselekcjonowane przepisy na koktajle — od ponadczasowych klasyków po odważne nowości.'),
('pl', 'seo.search_desc', 'Szukaj przepisów na koktajle według nazwy, składnika, tagu lub sprzętu.'),
('pl', 'hero.craft', 'Stwórz'),
('pl', 'hero.your_perfect', 'Swój Idealny'),
('pl', 'hero.cocktail', 'Koktajl'),
('pl', 'hero.subtitle', 'Odkryj starannie wyselekcjonowane przepisy — od ponadczasowych klasyków po odważne nowości.'),
('pl', 'hero.explore', 'Przeglądaj przepisy'),
('pl', 'home.featured', 'Polecane przepisy'),
('pl', 'home.featured_sub', 'Nasze najpopularniejsze wybory'),
('pl', 'home.view_all', 'Zobacz wszystkie'),
('pl', 'common.loading', 'Ładowanie...'),
('pl', 'common.all', 'Wszystkie'),
('pl', 'common.back_home', 'Wróć na stronę główną'),
('pl', 'common.show_less', 'Pokaż mniej'),
('pl', 'common.read_more', 'Czytaj więcej'),
('pl', 'recipe.not_found', 'Przepis nie znaleziony'),
('pl', 'recipe.ingredients', 'Składniki'),
('pl', 'recipe.recipe', 'Przepis'),
('pl', 'recipe.bar_tools', 'Narzędzia barowe'),
('pl', 'recipe.recommended', 'Polecane drinki'),
('pl', 'recipe.reviews', 'Opinie'),
('pl', 'recipe.tools', 'Narzędzia'),
('pl', 'ingredient.not_found', 'Składnik nie znaleziony'),
('pl', 'ingredient.recipes_with', 'Przepisy ze składnikiem'),
('pl', 'ingredients.subtitle', 'Poznaj wszystkie składniki używane w naszych przepisach.'),
('pl', 'search.placeholder', 'Szukaj po nazwie, składniku, tagu, hashtagu, sprzęcie...'),
('pl', 'search.placeholder_short', 'Szukaj przepisów...'),
('pl', 'search.results', 'przepis(ów) znalezionych dla'),
('pl', 'search.no_results', 'Brak wyników'),
('pl', 'search.try_different', 'Spróbuj innych słów kluczowych lub przeglądaj kategorie.'),
('pl', 'search.start_typing', 'Zacznij pisać, aby wyszukać'),
('pl', 'search.hint', 'Szukaj po nazwie przepisu, składniku, tagu, hashtagu lub sprzęcie.'),
('pl', 'footer.contact', 'Skontaktuj się z nami'),
('pl', 'footer.rights', 'Wszelkie prawa zastrzeżone.'),
('pl', 'review.your_name', 'Twoje imię'),
('pl', 'review.write', 'Napisz swoją opinię...'),
('pl', 'review.rating', 'Ocena:'),
('pl', 'review.submit', 'Wyślij'),
('pl', 'review.sending', 'Wysyłanie...'),
('pl', 'review.empty', 'Brak opinii. Bądź pierwszy!'),
('pl', 'notfound.title', 'Strona nie znaleziona'),
('pl', 'notfound.back', 'Wróć na stronę główną'),
('pl', 'ingredients.no_results', 'Nie znaleziono składników'),
('pl', 'category.no_more', 'Brak kolejnych przepisów'),
('pl', 'category.loading_more', 'Ładowanie przepisów...'),
-- ===== UKRAINIAN =====
('uk', 'nav.cocktails', 'Коктейлі'),
('uk', 'nav.shots', 'Шоти'),
('uk', 'nav.non_alcoholic', 'Безалкогольні'),
('uk', 'nav.ingredients', 'Інгредієнти'),
('uk', 'nav.search', 'Пошук'),
('uk', 'cat.cocktails', 'Коктейлі'),
('uk', 'cat.shots', 'Шоти'),
('uk', 'cat.non-alcoholic', 'Безалкогольні'),
('uk', 'cat.cocktails_desc', 'Класичні та сучасні рецепти коктейлів, приготовані до досконалості.'),
('uk', 'cat.shots_desc', 'Швидкі, сміливі та ідеальні для свят.'),
('uk', 'cat.non-alcoholic_desc', 'Освіжаючі безалкогольні напої на будь-який випадок.'),
('uk', 'seo.home_title', 'Cocktail Craft — Відкрийте ідеальні рецепти коктейлів'),
('uk', 'seo.home_desc', 'Досліджуйте ретельно підібрані рецепти коктейлів — від класики до сміливих новинок.'),
('uk', 'seo.search_desc', 'Шукайте рецепти коктейлів за назвою, інгредієнтом, тегом або обладнанням.'),
('uk', 'hero.craft', 'Створи'),
('uk', 'hero.your_perfect', 'Свій Ідеальний'),
('uk', 'hero.cocktail', 'Коктейль'),
('uk', 'hero.subtitle', 'Відкривайте ретельно підібрані рецепти — від класики до сміливих новинок.'),
('uk', 'hero.explore', 'Переглянути рецепти'),
('uk', 'home.featured', 'Рекомендовані рецепти'),
('uk', 'home.featured_sub', 'Наші найпопулярніші добірки'),
('uk', 'home.view_all', 'Дивитись усі'),
('uk', 'common.loading', 'Завантаження...'),
('uk', 'common.all', 'Усі'),
('uk', 'common.back_home', 'На головну'),
('uk', 'common.show_less', 'Згорнути'),
('uk', 'common.read_more', 'Читати далі'),
('uk', 'recipe.not_found', 'Рецепт не знайдено'),
('uk', 'recipe.ingredients', 'Інгредієнти'),
('uk', 'recipe.recipe', 'Рецепт'),
('uk', 'recipe.bar_tools', 'Барні інструменти'),
('uk', 'recipe.recommended', 'Рекомендовані напої'),
('uk', 'recipe.reviews', 'Відгуки'),
('uk', 'recipe.tools', 'Інструменти'),
('uk', 'ingredient.not_found', 'Інгредієнт не знайдено'),
('uk', 'ingredient.recipes_with', 'Рецепти з'),
('uk', 'ingredients.subtitle', 'Ознайомтесь з усіма інгредієнтами наших рецептів.'),
('uk', 'search.placeholder', 'Шукати за назвою, інгредієнтом, тегом, хештегом, обладнанням...'),
('uk', 'search.placeholder_short', 'Шукати рецепти...'),
('uk', 'search.results', 'рецепт(ів) знайдено для'),
('uk', 'search.no_results', 'Нічого не знайдено'),
('uk', 'search.try_different', 'Спробуйте інші ключові слова або перегляньте категорії.'),
('uk', 'search.start_typing', 'Почніть вводити для пошуку'),
('uk', 'search.hint', 'Шукайте за назвою рецепту, інгредієнтом, тегом, хештегом або обладнанням.'),
('uk', 'footer.contact', 'Зв''яжіться з нами'),
('uk', 'footer.rights', 'Усі права захищені.'),
('uk', 'review.your_name', 'Ваше ім''я'),
('uk', 'review.write', 'Напишіть свій відгук...'),
('uk', 'review.rating', 'Оцінка:'),
('uk', 'review.submit', 'Надіслати'),
('uk', 'review.sending', 'Надсилання...'),
('uk', 'review.empty', 'Ще немає відгуків. Будьте першим!'),
('uk', 'notfound.title', 'Сторінку не знайдено'),
('uk', 'notfound.back', 'На головну'),
('uk', 'ingredients.no_results', 'Інгредієнти не знайдено'),
('uk', 'category.no_more', 'Більше немає рецептів'),
('uk', 'category.loading_more', 'Завантаження рецептів...')
ON CONFLICT DO NOTHING;
